# Generated by Django 3.2.18 on 2023-04-10 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player_profile', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('studentid', models.CharField(max_length=10, unique=True, verbose_name='학번')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='이름')),
                ('school', models.CharField(blank=True, choices=[('Yonsei', '연세대학교'), ('Korea', '고려대학교')], max_length=20, verbose_name='학교')),
                ('sports', models.CharField(blank=True, choices=[('soccer', '축구'), ('basketball', '농구'), ('baseball', '야구'), ('icehockey', '아이스하키'), ('rugby', '럭비')], max_length=20, verbose_name='종목')),
                ('major', models.CharField(blank=True, max_length=20, verbose_name='학과')),
                ('idcard', models.ImageField(blank=True, upload_to='idcard/')),
                ('idprofile', models.ImageField(blank=True, upload_to='idprofile/')),
                ('info_1', models.CharField(blank=True, max_length=5, verbose_name='1_나이')),
                ('info_2', models.CharField(blank=True, max_length=5, verbose_name='2_키')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='등록날짜')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='마지막로그인')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('profile', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='player_profile.profile')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'studentid',
                'verbose_name_plural': 'users유저들',
            },
        ),
    ]
