# Generated by Django 4.2 on 2023-04-10 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player_profile', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='idcard',
            field=models.ImageField(blank=True, upload_to='idcard/', verbose_name='학생증 확인'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='idprofile',
            field=models.ImageField(blank=True, upload_to='idprofile/', verbose_name='프로필사진'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='승인완료'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='User_set', to='player_profile.profile'),
        ),
    ]
