# Generated by Django 3.2.18 on 2023-05-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_idcard_alter_customuser_idprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='idcard',
            field=models.ImageField(blank=True, default='', upload_to='idcard/', verbose_name='학생증 확인'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='idprofile',
            field=models.ImageField(blank=True, default='', upload_to='idprofile/', verbose_name='프로필사진'),
        ),
    ]
