# Generated by Django 3.2.18 on 2023-04-10 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=5)),
                ('school', models.CharField(choices=[('Yonsei', '연세대학교'), ('Korea', '고려대학교')], max_length=10)),
                ('sports', models.CharField(choices=[('soccer', '축구'), ('basketball', '농구'), ('baseball', '야구'), ('icehockey', '아이스하키'), ('rugby', '럭비')], max_length=10)),
                ('position', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player_profile.profile')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
